// Copyright 2000-2021 Mark H. P. Lord

#ifndef PRIME_ANSIESCAPES_H
#define PRIME_ANSIESCAPES_H

#include "Config.h"

#define PRIME_ANSI_CSI "\x1b["

#define PRIME_ANSI_BOLD "1"
#define PRIME_ANSI_FAINT "2"
#define PRIME_ANSI_ITALIC "3"
#define PRIME_ANSI_UNDERLINE "4"

#define PRIME_ANSI_CLEAR_ATTRIBUTES "0"

#define PRIME_ANSI_FG_BLACK "30"
#define PRIME_ANSI_FG_RED "31"
#define PRIME_ANSI_FG_GREEN "32"
#define PRIME_ANSI_FG_YELLOW "33"
#define PRIME_ANSI_FG_BLUE "34"
#define PRIME_ANSI_FG_MAGENTA "35"
#define PRIME_ANSI_FG_CYAN "36"
#define PRIME_ANSI_FG_WHITE "37"

#define PRIME_ANSI_BG_BLACK "40"
#define PRIME_ANSI_BG_RED "41"
#define PRIME_ANSI_BG_GREEN "42"
#define PRIME_ANSI_BG_YELLOW "43"
#define PRIME_ANSI_BG_BLUE "44"
#define PRIME_ANSI_BG_MAGENTA "45"
#define PRIME_ANSI_BG_CYAN "46"
#define PRIME_ANSI_BG_WHITE "47"

#define PRIME_ANSI_FG_BRIGHT_BLACK "90"
#define PRIME_ANSI_FG_BRIGHT_RED "91"
#define PRIME_ANSI_FG_BRIGHT_GREEN "92"
#define PRIME_ANSI_FG_BRIGHT_YELLOW "93"
#define PRIME_ANSI_FG_BRIGHT_BLUE "94"
#define PRIME_ANSI_FG_BRIGHT_MAGENTA "95"
#define PRIME_ANSI_FG_BRIGHT_CYAN "96"
#define PRIME_ANSI_FG_BRIGHT_WHITE "97"

#define PRIME_ANSI_SET_ATTRIBUTE "m"

#define PRIME_ANSI_SEQUENCE_RESET_ATTRIBUTES PRIME_ANSI_CSI PRIME_ANSI_CLEAR_ATTRIBUTES PRIME_ANSI_SET_ATTRIBUTE

#endif
